# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# https://www.elastic.co/guide/en/kibana/6.7/development-plugin-resources.html
# The Kibana directory must be named kibana, and your plugin directory must be 
# located within the sibling kibana-extra folder, for example:
# .
# ├── kibana
# ├── kibana-extra/foo-plugin
# └── kibana-extra/bar-plugin

steps:
- checkout: self
  path: kibana-extra/kibana-time-plugin

- task: CmdLine@2
  displayName: 'Clone Kibana'
  inputs:
    script: |
      git clone --depth 1 --branch 6.5 https://github.com/elastic/kibana.git
      pwd
      ls -la
    workingDirectory: $(Pipeline.Workspace)

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '8.14.0'

- task: YarnInstaller@3
  displayName: 'Install Yarn'
  inputs:
    versionSpec: '1.x'

# - task: Yarn@3
#   displayName: 'Install npm dependencies'

- task: Yarn@3
  displayName: 'Kibana bootstrap'
  inputs:
    arguments: 'run kbn bootstrap'

- task: Bower@0
  displayName: 'Install bower dependencies'
  inputs:
    command: 'install'
    bowerjson: 'bower.json'

- task: CmdLine@2
  inputs:
    script: |
      ls -la
      ls -la node_modules
      ls -la node_modules/.bin

- task: Yarn@3
  displayName: 'Build plugin'
  inputs:
    arguments: 'run build'