# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- 6.5

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    kibana_6_5_3:
      kibana_version: 6.5.3
      kibana_branch: 6.5
      node_version: 8.14.0
      build_version: $(kibana_version)

# https://www.elastic.co/guide/en/kibana/6.7/development-plugin-resources.html
# The Kibana directory must be named kibana, and your plugin directory must be 
# located within the sibling kibana-extra folder, for example:
# .
# ├── kibana
# ├── kibana-extra/foo-plugin
# └── kibana-extra/bar-plugin

steps:
- checkout: self
  path: kibana-extra/kibana-time-plugin

- task: CmdLine@2
  displayName: 'Clone Kibana'
  inputs:
    script: 'git clone --depth 1 --branch $(kibana_branch) https://github.com/elastic/kibana.git $(Pipeline.Workspace)/kibana'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '$(node_version)'

- task: YarnInstaller@3
  displayName: 'Install Yarn'
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: 'Kibana bootstrap'
  inputs:
    arguments: 'run kbn bootstrap'

- task: Bower@0
  displayName: 'Install bower dependencies'
  inputs:
    command: 'install'
    bowerjson: 'bower.json'

- task: Yarn@3
  displayName: 'Set plugin version'
  inputs:
    arguments: 'version --new-version $(build_version) --no-git-tag-version'

- task: CmdLine@2
  displayName: 'Set Kibana version'
  inputs:
    script: mv package.json package.json.bak && jq '.kibana.version = "$(kibana_version)"' package.json.bak > package.json

- task: Yarn@3
  displayName: 'Build plugin'
  inputs:
    arguments: 'run build'

# - task: docker@1
#   displayName: 'Test plugin installation'
#   inputs:
#     command: 'Run an image'
#     imageName: 'kibana:$(kibana_version)'
#     volumes: '$(Build.BinariesDirectory)/build:/build'
#     containerCommand: 'bin/kibana-plugin install file:///build/*.zip'

- task: Docker@2
  inputs:
    command: 'build'
    arguments: 'KIBANA_VERSION=$(kibana_version)'

- task: CopyFiles@2
  displayName: 'Copy build artifacts'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build'
    contents: '*.zip'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@0
  displayName: 'Publish master'
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'GitHub release'
    repositoryName: '$(Build.Repository.Name)'
    isPreRelease: true
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.BuildNumber)'
    compareWith: 'lastFullRelease'
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
